name: Run Python Script Daily

on:
  schedule:
    - cron: '28 7 * * *'  # Runs at 10:00 AM IST (UTC+5:30)
  workflow_dispatch:  # optional: allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug files
        run: |
            pwd
            ls -la

      - name: Run Python script
        run: |
          python main.py
